// Embeds Docs/house-format.md into the build so the server works as a single file (no docs folder needed).
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const guide = readFileSync(join(here, "..", "..", "Docs", "house-format.md"), "utf8");
writeFileSync(join(here, "..", "src", "guide.generated.ts"),
  `// generated by scripts/embed-guide.mjs from Docs/house-format.md — do not edit\nexport const FORMAT_GUIDE = ${JSON.stringify(guide)};\n`);
console.log(`embedded guide: ${guide.length} chars`);
